DELETE FROM Matches;
DELETE FROM Players;

ALTER TABLE Players ALTER COLUMN id RESTART WITH 1;
ALTER TABLE Matches ALTER COLUMN id RESTART WITH 1;

INSERT INTO Players (name) VALUES ('Novak Djokovic');
INSERT INTO Players (name) VALUES ('Carlos Alcaraz');
INSERT INTO Players (name) VALUES ('Jannik Sinner');
INSERT INTO Players (name) VALUES ('Daniil Medvedev');
INSERT INTO Players (name) VALUES ('Alexander Zverev');
INSERT INTO Players (name) VALUES ('Andrey Rublev');
INSERT INTO Players (name) VALUES ('Holger Rune');
INSERT INTO Players (name) VALUES ('Casper Ruud');
INSERT INTO Players (name) VALUES ('Hubert Hurkacz');
INSERT INTO Players (name) VALUES ('Alex de Minaur');
INSERT INTO Players (name) VALUES ('Taylor Fritz');
INSERT INTO Players (name) VALUES ('Grigor Dimitrov');
INSERT INTO Players (name) VALUES ('Stefanos Tsitsipas');
INSERT INTO Players (name) VALUES ('Ben Shelton');
INSERT INTO Players (name) VALUES ('Frances Tiafoe');
INSERT INTO Players (name) VALUES ('Tommy Paul');
INSERT INTO Players (name) VALUES ('Karen Khachanov');
INSERT INTO Players (name) VALUES ('Sebastian Baez');
INSERT INTO Players (name) VALUES ('Ugo Humbert');
INSERT INTO Players (name) VALUES ('Alexander Bublik');
INSERT INTO Players (name) VALUES ('Adrian Mannarino');
INSERT INTO Players (name) VALUES ('Francisco Cerundolo');
INSERT INTO Players (name) VALUES ('Nicolas Jarry');
INSERT INTO Players (name) VALUES ('Lorenzo Musetti');
INSERT INTO Players (name) VALUES ('Sebastian Korda');
INSERT INTO Players (name) VALUES ('Alejandro Davidovich Fokina');
INSERT INTO Players (name) VALUES ('Jan-Lennard Struff');
INSERT INTO Players (name) VALUES ('Tallon Griekspoor');
INSERT INTO Players (name) VALUES ('Jiri Lehecka');
INSERT INTO Players (name) VALUES ('Felix Auger-Aliassime');
INSERT INTO Players (name) VALUES ('Alexei Popyrin');
INSERT INTO Players (name) VALUES ('Tomas Martin Etcheverry');
INSERT INTO Players (name) VALUES ('Lorenzo Sonego');
INSERT INTO Players (name) VALUES ('Christopher Eubanks');
INSERT INTO Players (name) VALUES ('Daniel Evans');
INSERT INTO Players (name) VALUES ('Mackenzie McDonald');
INSERT INTO Players (name) VALUES ('Aslan Karatsev');
INSERT INTO Players (name) VALUES ('Yoshihito Nishioka');
INSERT INTO Players (name) VALUES ('Miomir Kecmanovic');
INSERT INTO Players (name) VALUES ('Max Purcell');
INSERT INTO Players (name) VALUES ('Andy Murray');
INSERT INTO Players (name) VALUES ('Stan Wawrinka');
INSERT INTO Players (name) VALUES ('Dominic Thiem');
INSERT INTO Players (name) VALUES ('Gaël Monfils');
INSERT INTO Players (name) VALUES ('Richard Gasquet');
INSERT INTO Players (name) VALUES ('Roberto Bautista Agut');
INSERT INTO Players (name) VALUES ('John Isner');
INSERT INTO Players (name) VALUES ('Kevin Anderson');
INSERT INTO Players (name) VALUES ('Marin Cilic');
INSERT INTO Players (name) VALUES ('Milos Raonic');
INSERT INTO Players (name) VALUES ('Kei Nishikori');
INSERT INTO Players (name) VALUES ('David Goffin');
INSERT INTO Players (name) VALUES ('Pablo Carreno Busta');
INSERT INTO Players (name) VALUES ('Diego Schwartzman');
INSERT INTO Players (name) VALUES ('Fabio Fognini');
INSERT INTO Players (name) VALUES ('Nick Kyrgios');
INSERT INTO Players (name) VALUES ('Borna Coric');
INSERT INTO Players (name) VALUES ('Reilly Opelka');
INSERT INTO Players (name) VALUES ('Jenson Brooksby');
INSERT INTO Players (name) VALUES ('Brandon Nakashima');
INSERT INTO Players (name) VALUES ('Emil Ruusuvuori');
INSERT INTO Players (name) VALUES ('Arthur Fils');
INSERT INTO Players (name) VALUES ('Luca Van Assche');
INSERT INTO Players (name) VALUES ('Dominik Koepfer');
INSERT INTO Players (name) VALUES ('Marcos Giron');
INSERT INTO Players (name) VALUES ('Jeffrey John Wolf');
INSERT INTO Players (name) VALUES ('Jordan Thompson');
INSERT INTO Players (name) VALUES ('Aleksandar Vukic');
INSERT INTO Players (name) VALUES ('Christopher O''Connell');
INSERT INTO Players (name) VALUES ('Rinky Hijikata');
INSERT INTO Players (name) VALUES ('Thanasi Kokkinakis');
INSERT INTO Players (name) VALUES ('Alex Bolt');
INSERT INTO Players (name) VALUES ('James Duckworth');
INSERT INTO Players (name) VALUES ('Maxime Cressy');
INSERT INTO Players (name) VALUES ('Botic van de Zandschulp');
INSERT INTO Players (name) VALUES ('Marton Fucsovics');
INSERT INTO Players (name) VALUES ('Soonwoo Kwon');
INSERT INTO Players (name) VALUES ('Yibing Wu');
INSERT INTO Players (name) VALUES ('Zhizhen Zhang');
INSERT INTO Players (name) VALUES ('Juncheng Shang');
INSERT INTO Players (name) VALUES ('Mikhail Kukushkin');
INSERT INTO Players (name) VALUES ('Pavel Kotov');
INSERT INTO Players (name) VALUES ('Roman Safiullin');
INSERT INTO Players (name) VALUES ('Ilya Ivashka');
INSERT INTO Players (name) VALUES ('Lucas Pouille');
INSERT INTO Players (name) VALUES ('Jo-Wilfried Tsonga');
INSERT INTO Players (name) VALUES ('Gilles Simon');
INSERT INTO Players (name) VALUES ('Feliciano Lopez');
INSERT INTO Players (name) VALUES ('Fernando Verdasco');
INSERT INTO Players (name) VALUES ('Philipp Kohlschreiber');
INSERT INTO Players (name) VALUES ('Sam Querrey');
INSERT INTO Players (name) VALUES ('Steve Johnson');
INSERT INTO Players (name) VALUES ('Jack Sock');
INSERT INTO Players (name) VALUES ('Denis Shapovalov');
INSERT INTO Players (name) VALUES ('Vasek Pospisil');
INSERT INTO Players (name) VALUES ('Peter Polansky');
INSERT INTO Players (name) VALUES ('Brayden Schnur');
INSERT INTO Players (name) VALUES ('Filip Peliwo');
INSERT INTO Players (name) VALUES ('Matteo Berrettini');
INSERT INTO Players (name) VALUES ('Jiri Vesely');
INSERT INTO Players (name) VALUES ('Pierre-Hugues Herbert');

INSERT INTO Matches (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO Matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO Matches (player1, player2, winner) VALUES (7, 8, 7);
INSERT INTO Matches (player1, player2, winner) VALUES (9, 10, 9);
INSERT INTO Matches (player1, player2, winner) VALUES (11, 12, 11);
INSERT INTO Matches (player1, player2, winner) VALUES (13, 14, 13);
INSERT INTO Matches (player1, player2, winner) VALUES (15, 16, 15);
INSERT INTO Matches (player1, player2, winner) VALUES (17, 18, 17);
INSERT INTO Matches (player1, player2, winner) VALUES (19, 20, 19);
INSERT INTO Matches (player1, player2, winner) VALUES (2, 3, 2);
INSERT INTO Matches (player1, player2, winner) VALUES (4, 5, 4);
INSERT INTO Matches (player1, player2, winner) VALUES (6, 7, 6);
INSERT INTO Matches (player1, player2, winner) VALUES (8, 9, 8);
INSERT INTO Matches (player1, player2, winner) VALUES (10, 11, 10);
INSERT INTO Matches (player1, player2, winner) VALUES (12, 13, 12);
INSERT INTO Matches (player1, player2, winner) VALUES (14, 15, 14);
INSERT INTO Matches (player1, player2, winner) VALUES (16, 17, 16);
INSERT INTO Matches (player1, player2, winner) VALUES (18, 19, 18);
INSERT INTO Matches (player1, player2, winner) VALUES (20, 1, 1);
INSERT INTO Matches (player1, player2, winner) VALUES (21, 22, 21);
INSERT INTO Matches (player1, player2, winner) VALUES (23, 24, 23);
INSERT INTO Matches (player1, player2, winner) VALUES (25, 26, 25);
INSERT INTO Matches (player1, player2, winner) VALUES (27, 28, 27);
INSERT INTO Matches (player1, player2, winner) VALUES (29, 30, 29);
INSERT INTO Matches (player1, player2, winner) VALUES (31, 32, 31);
INSERT INTO Matches (player1, player2, winner) VALUES (33, 34, 33);
INSERT INTO Matches (player1, player2, winner) VALUES (35, 36, 35);
INSERT INTO Matches (player1, player2, winner) VALUES (37, 38, 37);
INSERT INTO Matches (player1, player2, winner) VALUES (39, 40, 39);
INSERT INTO Matches (player1, player2, winner) VALUES (41, 42, 41);
INSERT INTO Matches (player1, player2, winner) VALUES (43, 44, 43);
INSERT INTO Matches (player1, player2, winner) VALUES (45, 46, 45);
INSERT INTO Matches (player1, player2, winner) VALUES (47, 48, 47);
INSERT INTO Matches (player1, player2, winner) VALUES (49, 50, 49);
INSERT INTO Matches (player1, player2, winner) VALUES (51, 52, 51);
INSERT INTO Matches (player1, player2, winner) VALUES (53, 54, 53);
INSERT INTO Matches (player1, player2, winner) VALUES (55, 56, 55);
INSERT INTO Matches (player1, player2, winner) VALUES (57, 58, 57);
INSERT INTO Matches (player1, player2, winner) VALUES (59, 60, 59);
INSERT INTO Matches (player1, player2, winner) VALUES (61, 62, 61);
INSERT INTO Matches (player1, player2, winner) VALUES (63, 64, 63);
INSERT INTO Matches (player1, player2, winner) VALUES (65, 66, 65);
INSERT INTO Matches (player1, player2, winner) VALUES (67, 68, 67);
INSERT INTO Matches (player1, player2, winner) VALUES (69, 70, 69);
INSERT INTO Matches (player1, player2, winner) VALUES (71, 72, 71);
INSERT INTO Matches (player1, player2, winner) VALUES (73, 74, 73);
INSERT INTO Matches (player1, player2, winner) VALUES (75, 76, 75);
INSERT INTO Matches (player1, player2, winner) VALUES (77, 78, 77);
INSERT INTO Matches (player1, player2, winner) VALUES (79, 80, 79);
INSERT INTO Matches (player1, player2, winner) VALUES (81, 82, 81);
INSERT INTO Matches (player1, player2, winner) VALUES (83, 84, 83);
INSERT INTO Matches (player1, player2, winner) VALUES (85, 86, 85);
INSERT INTO Matches (player1, player2, winner) VALUES (87, 88, 87);
INSERT INTO Matches (player1, player2, winner) VALUES (89, 90, 89);
INSERT INTO Matches (player1, player2, winner) VALUES (91, 92, 91);
INSERT INTO Matches (player1, player2, winner) VALUES (93, 94, 93);
INSERT INTO Matches (player1, player2, winner) VALUES (95, 96, 95);
INSERT INTO Matches (player1, player2, winner) VALUES (97, 98, 97);
INSERT INTO Matches (player1, player2, winner) VALUES (99, 100, 99);